// ExtService is used to pass client request between gateways with Apron network
// The message contains

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.4
// source: ext_service.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExtServiceData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// service_name is used for Apron, which indicates what service the package is from
	ServiceName string `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	// request_id used to identify connection with service in SA side
	RequestId string `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// unique message, used for tracing complete flow of message
	MsgId string `protobuf:"bytes,3,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	// content_type is used by service handler, to determine how to decode content field
	ContentType uint32 `protobuf:"varint,10,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	// content contains serialized service data, which will parsed to service specified data structure based on services
	Content []byte `protobuf:"bytes,20,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *ExtServiceData) Reset() {
	*x = ExtServiceData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ext_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExtServiceData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtServiceData) ProtoMessage() {}

func (x *ExtServiceData) ProtoReflect() protoreflect.Message {
	mi := &file_ext_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtServiceData.ProtoReflect.Descriptor instead.
func (*ExtServiceData) Descriptor() ([]byte, []int) {
	return file_ext_service_proto_rawDescGZIP(), []int{0}
}

func (x *ExtServiceData) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ExtServiceData) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ExtServiceData) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *ExtServiceData) GetContentType() uint32 {
	if x != nil {
		return x.ContentType
	}
	return 0
}

func (x *ExtServiceData) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

var File_ext_service_proto protoreflect.FileDescriptor

var file_ext_service_proto_rawDesc = []byte{
	0x0a, 0x11, 0x65, 0x78, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xa6, 0x01, 0x0a, 0x0e, 0x45, 0x78, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x6d, 0x73, 0x67, 0x5f,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x12,
	0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x14, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x42, 0x1e, 0x5a, 0x1c,
	0x61, 0x70, 0x72, 0x6f, 0x6e, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x67, 0x61,
	0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ext_service_proto_rawDescOnce sync.Once
	file_ext_service_proto_rawDescData = file_ext_service_proto_rawDesc
)

func file_ext_service_proto_rawDescGZIP() []byte {
	file_ext_service_proto_rawDescOnce.Do(func() {
		file_ext_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_ext_service_proto_rawDescData)
	})
	return file_ext_service_proto_rawDescData
}

var file_ext_service_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ext_service_proto_goTypes = []interface{}{
	(*ExtServiceData)(nil), // 0: ExtServiceData
}
var file_ext_service_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ext_service_proto_init() }
func file_ext_service_proto_init() {
	if File_ext_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ext_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExtServiceData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ext_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ext_service_proto_goTypes,
		DependencyIndexes: file_ext_service_proto_depIdxs,
		MessageInfos:      file_ext_service_proto_msgTypes,
	}.Build()
	File_ext_service_proto = out.File
	file_ext_service_proto_rawDesc = nil
	file_ext_service_proto_goTypes = nil
	file_ext_service_proto_depIdxs = nil
}
